Switch to brotli to brotlipy
The original brotli PyPi package seems to have some sort of DLL
errors:

    ImportError: DLL load failed: The specified module could not be
    found.

Switching to the brotlipy package fixes this. Unsure if the DLL
error is specific to this one computer or is it persistent across
all Windows systems.